package com.hyperprotect.mixin.intercept.containers;

import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.server.core.Message;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import com.hypixel.hytale.builtin.adventure.shop.barter.BarterPage;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Redirect;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.atomic.AtomicReferenceArray;

/**
 * Intercepts barter/trade execution in BarterPage.handleDataEvent() — slot 29.
 *
 * <p>Uses {@code @Redirect} on {@code data.getQuantity()} instead of {@code @Inject}
 * to avoid runtime dependency on {@code CallbackInfo} (not on TransformingClassLoader
 * classpath). If the hook denies the trade, returns 0 which triggers the method's
 * built-in {@code requestedQuantity <= 0} early return.
 *
 * <p>Hook contract (barter_trade slot):
 * <pre>
 *   int evaluateTrade(UUID player, String world, int x, int y, int z)
 *     Verdict: 0=ALLOW, 1=DENY_WITH_MESSAGE, 2=DENY_SILENT
 * </pre>
 *
 * <p>Fail-open: no hook = allow all trades.
 */
@Mixin(BarterPage.class)
public class BarterTradeInterceptor {

    @Unique
    private static final AtomicLong faultCount = new AtomicLong();

    @Unique
    private static volatile Object[] hookCache;

    @Unique
    private static final MethodType EVALUATE_TYPE = MethodType.methodType(
            int.class, UUID.class, String.class, int.class, int.class, int.class);

    @Unique
    private static final MethodType FETCH_REASON_TYPE = MethodType.methodType(
            String.class, UUID.class, String.class, int.class, int.class, int.class);

    static {
        System.setProperty("hyperprotect.intercept.barter_trade", "true");
    }

    @Unique
    @SuppressWarnings("unchecked")
    private static Object getBridge(int slot) {
        try {
            Object bridge = System.getProperties().get("hyperprotect.bridge");
            if (bridge == null) return null;
            return ((AtomicReferenceArray<Object>) bridge).get(slot);
        } catch (Exception e) {
            return null;
        }
    }

    @Unique
    private static void reportFault(Throwable t) {
        long count = faultCount.incrementAndGet();
        if (count == 1 || count % 100 == 0) {
            System.err.println("[HyperProtect] BarterTradeInterceptor error #" + count + ": " + t);
            t.printStackTrace(System.err);
        }
    }

    @Unique
    private static Object[] resolveHook() {
        Object[] cached = hookCache;
        Object impl = getBridge(29); // barter_trade
        if (impl == null) {
            hookCache = null;
            return null;
        }
        if (cached != null && cached[0] == impl) {
            return cached;
        }
        try {
            MethodHandle primary = MethodHandles.publicLookup().findVirtual(
                impl.getClass(), "evaluateTrade", EVALUATE_TYPE);
            MethodHandle secondary = null;
            try {
                secondary = MethodHandles.publicLookup().findVirtual(
                    impl.getClass(), "fetchTradeDenyReason", FETCH_REASON_TYPE);
            } catch (NoSuchMethodException ignored) {}
            cached = new Object[] { impl, primary, secondary };
            hookCache = cached;
            return cached;
        } catch (Exception e) {
            reportFault(e);
            return null;
        }
    }

    /**
     * Redirects data.getQuantity() inside handleDataEvent to gate trade permission.
     * If the hook denies, returns 0 which triggers the method's built-in
     * {@code requestedQuantity <= 0} early return — effectively canceling the trade
     * without referencing any Mixin library classes in the generated bytecode.
     *
     * <p>The enclosing method params (ref, store, data) are captured after the
     * redirected call's receiver to provide player context for permission checks.
     */
    @Redirect(
        method = "handleDataEvent",
        at = @At(
            value = "INVOKE",
            target = "Lcom/hypixel/hytale/builtin/adventure/shop/barter/BarterPage$BarterEventData;getQuantity()I"
        ),
        require = 0
    )
    private int gateTrade(BarterPage.BarterEventData eventData,
                          Ref<EntityStore> ref, Store<EntityStore> store,
                          BarterPage.BarterEventData dataParam) {
        int quantity = eventData.getQuantity(); // Call original

        try {
            Object[] hook = resolveHook();
            if (hook == null) return quantity; // No hook = allow

            // Get player UUID and position
            UUID playerUuid = null;
            String worldName = null;
            int x = 0, y = 0, z = 0;

            try {
                PlayerRef pRef = store.getComponent(ref, PlayerRef.getComponentType());
                if (pRef != null) {
                    playerUuid = pRef.getUuid();
                    var transform = pRef.getTransform();
                    if (transform != null) {
                        var pos = transform.getPosition();
                        x = (int) pos.x;
                        y = (int) pos.y;
                        z = (int) pos.z;
                    }
                }
                var world = store.getExternalData().getWorld();
                if (world != null) {
                    worldName = world.getName();
                }
            } catch (Exception ignored) {}

            if (playerUuid == null || worldName == null) return quantity;

            int verdict = (int) ((MethodHandle) hook[1]).invoke(
                    hook[0], playerUuid, worldName, x, y, z);

            if (verdict < 0) return quantity; // Fail-open

            if (verdict == 1 || verdict == 2) {
                if (verdict == 1 && hook.length > 2 && hook[2] != null) {
                    try {
                        String reason = (String) ((MethodHandle) hook[2]).invoke(
                                hook[0], playerUuid, worldName, x, y, z);
                        if (reason != null && !reason.isEmpty()) {
                            Object fmtHandle = getBridge(15);
                            if (fmtHandle instanceof MethodHandle mh) {
                                Player player = store.getComponent(ref, Player.getComponentType());
                                if (player != null) {
                                    Message msg = (Message) mh.invoke(reason);
                                    player.sendMessage(msg);
                                }
                            }
                        }
                    } catch (Throwable ignored) {}
                }
                return 0; // DENY — return 0 to trigger early return (requestedQuantity <= 0)
            }
        } catch (Throwable t) {
            reportFault(t);
            // Fail-open: allow trade
        }
        return quantity;
    }
}
